In [6]:
import os

print(os.getcwd())

c:\projects\Game-Recommendation-System\notebook

In [80]:
import pandas as pd

recommendations = pd.read_csv("../data/recommendations.csv")
games = pd.read_csv("../data/games.csv")
users = pd.read_csv("../data/users.csv")
print(recommendations.head())
print(games.head())
print(users.head())

KeyboardInterrupt:

In [ ]:
gamesgenres = pd.read_csv("../data/games_inc.csv")

KeyError: 'AppID'

In [133]:
correct_columns = [
    'AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU',
    'Required age', 'Price', 'Discount', 'DLC count', 'About the game',
    'Supported languages', 'Full audio languages', 'Reviews', 'Header image',
    'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux',
    'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative',
    'Score rank', 'Achievements', 'Recommendations', 'Notes',
    'Average playtime forever', 'Average playtime two weeks',
    'Median playtime forever', 'Median playtime two weeks',
    'Developers', 'Publishers', 'Categories', 'Genres', 'Tags',
    'Screenshots', 'Movies'
]

gamesgenres = pd.read_csv(
    "../data/games_inc.csv",
    header=0,          # 기존 헤더 줄은 버리고
    names=correct_columns  # 이 이름들을 강제로 매핑
)

print(gamesgenres.shape)  # (125855, 40) 이 나오면 정상

(125855, 40)

In [134]:
gamesgenres.head()

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [72]:
print(gamesgenres.columns.tolist())

['AppID', 'Name', 'Release date', 'Estimated owners', 'Peak CCU', 'Required age', 'Price', 'DiscountDLC count', 'About the game', 'Supported languages', 'Full audio languages', 'Reviews', 'Header image', 'Website', 'Support url', 'Support email', 'Windows', 'Mac', 'Linux', 'Metacritic score', 'Metacritic url', 'User score', 'Positive', 'Negative', 'Score rank', 'Achievements', 'Recommendations', 'Notes', 'Average playtime forever', 'Average playtime two weeks', 'Median playtime forever', 'Median playtime two weeks', 'Developers', 'Publishers', 'Categories', 'Genres', 'Tags', 'Screenshots', 'Movies']

In [135]:
gamesgenres.info()
gamesgenres.describe()
gamesgenres.columns
gamesgenres.head()

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 40 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   AppID                       125855 non-null  int64
 1   Name                        125854 non-null  str
 2   Release date                125855 non-null  str
 3   Estimated owners            125855 non-null  str
 4   Peak CCU                    125855 non-null  int64
 5   Required age                125855 non-null  int64
 6   Price                       125855 non-null  float64
 7   Discount                    125855 non-null  int64
 8   DLC count                   125855 non-null  int64
 9   About the game              117393 non-null  str
 10  Supported languages         125855 non-null  str
 11  Full audio languages        125855 non-null  str
 12  Reviews                     12181 non-null   str
 13  Header image                125774 non-null  str
 14  Website                     50520 non-null   str
 15  Support url                 55295 non-null   str
 16  Support email               103225 non-null  str
 17  Windows                     125855 non-null  bool
 18  Mac                         125855 non-null  bool
 19  Linux                       125855 non-null  bool
 20  Metacritic score            125855 non-null  int64
 21  Metacritic url              4258 non-null    str
 22  User score                  125855 non-null  int64
 23  Positive                    125855 non-null  int64
 24  Negative                    125855 non-null  int64
 25  Score rank                  40 non-null      float64
 26  Achievements                125855 non-null  int64
 27  Recommendations             125855 non-null  int64
 28  Notes                       23310 non-null   str
 29  Average playtime forever    125855 non-null  int64
 30  Average playtime two weeks  125855 non-null  int64
 31  Median playtime forever     125855 non-null  int64
 32  Median playtime two weeks   125855 non-null  int64
 33  Developers                  117406 non-null  str
 34  Publishers                  116933 non-null  str
 35  Categories                  116889 non-null  str
 36  Genres                      117432 non-null  str
 37  Tags                        83353 non-null   str
 38  Screenshots                 119828 non-null  str
 39  Movies                      0 non-null       float64
dtypes: bool(3), float64(3), int64(15), str(19)
memory usage: 35.9 MB

,AppID,Name,Release date,Estimated owners,Peak CCU,Required age,Price,Discount,DLC count,About the game,...,Average playtime two weeks,Median playtime forever,Median playtime two weeks,Developers,Publishers,Categories,Genres,Tags,Screenshots,Movies
0,2539430,Black Dragon Mage Playtest,"Aug 1, 2023",0 - 0,0,0,0.00,0,0,NaN,...,0,0,0,NaN,NaN,NaN,NaN,NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
1,496350,Supipara - Chapter 1 Spring Has Come!,"Jul 29, 2016",0 - 20000,0,0,5.24,65,0,"Springtime, April: when the cherry trees come ...",...,0,8,0,minori,MangaGamer,"Single-player,Steam Trading Cards,Steam Cloud,...",Adventure,"Adventure,Visual Novel,Anime,Cute",https://shared.akamai.steamstatic.com/store_it...,NaN
2,1034400,Mystery Solitaire The Black Raven,"May 6, 2019",0 - 20000,0,0,4.99,0,0,"Immerse yourself in the most beloved, mystical...",...,0,0,0,Somer Games,8floor,"Single-player,Family Sharing",Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...",https://shared.akamai.steamstatic.com/store_it...,NaN
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Oct 31, 2024",0 - 20000,1,0,8.99,0,1,"synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ...",...,0,0,0,유진게임즈,유진게임즈,"Single-player,Steam Achievements,Family Sharing","Casual,Indie,Simulation",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN
4,3631080,Maze Quest VR,"Apr 24, 2025",0 - 20000,0,0,4.99,0,0,Its not just a Maze; its a Quest! Enter the ca...,...,0,0,0,Reality Expanded LLC,Reality Expanded LLC,"Single-player,VR Only,Steam Leaderboards,Famil...","Action,Early Access",NaN,https://shared.akamai.steamstatic.com/store_it...,NaN

In [138]:
meta = gamesgenres[
    [
        "AppID",
        "Name",
        "Genres",
        "Tags",
        "Categories",
        "About the game"
    ]
].copy()

In [139]:
meta.info()
meta.describe()
meta.columns

<class 'pandas.DataFrame'>
RangeIndex: 125855 entries, 0 to 125854
Data columns (total 6 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   AppID           125855 non-null  int64
 1   Name            125854 non-null  str
 2   Genres          117432 non-null  str
 3   Tags            83353 non-null   str
 4   Categories      116889 non-null  str
 5   About the game  117393 non-null  str
dtypes: int64(1), str(5)
memory usage: 5.8 MB

Index(['AppID', 'Name', 'Genres', 'Tags', 'Categories', 'About the game'], dtype='str')

In [30]:
print(meta.isnull().sum())

AppID                 1
Name                  0
Genres             8423
Tags              42502
Categories         8966
About the game     8462
dtype: int64

In [ ]:
meta[meta['Name'].isnull()]

,AppID,Name,Genres,Tags,Categories,About the game
44432,396420,NaN,NaN,NaN,NaN,Spookeningは3Dの恐怖ゲームで、あなたは毎夜に死んでゴーストとして復活します。 村...

In [141]:
meta = meta.dropna(subset=["Name"])

In [146]:
meta["Genres"] = meta["Genres"].fillna("")
meta["Categories"] = meta["Categories"].fillna("")
meta["About the game"] = meta["About the game"].fillna("")
meta["Tags"] = meta["Tags"].fillna("")

In [147]:
meta.head()

,AppID,Name,Genres,Tags,Categories,About the game
0,2539430,Black Dragon Mage Playtest,,,,
1,496350,Supipara - Chapter 1 Spring Has Come!,Adventure,"Adventure,Visual Novel,Anime,Cute","Single-player,Steam Trading Cards,Steam Cloud,...","Springtime, April: when the cherry trees come ..."
2,1034400,Mystery Solitaire The Black Raven,Casual,"Casual,Card Game,Solitaire,Puzzle,Hidden Objec...","Single-player,Family Sharing","Immerse yourself in the most beloved, mystical..."
3,3292190,버튜버 파라노이아 - Vtuber Paranoia,"Casual,Indie,Simulation",,"Single-player,Steam Achievements,Family Sharing","synopsis 'Hello, I'm Hiyoro, a new YouTuber!' ..."
4,3631080,Maze Quest VR,"Action,Early Access",,"Single-player,VR Only,Steam Leaderboards,Famil...",Its not just a Maze; its a Quest! Enter the ca...

In [149]:
print(meta.columns.tolist())

['AppID', 'Name', 'Genres', 'Tags', 'Categories', 'About the game']

In [152]:
meta.iloc[0]

AppID                                2539430
Name              Black Dragon Mage Playtest
Genres
Tags
Categories
About the game
Name: 0, dtype: object

In [150]:
gamesgenres.iloc[0]

AppID                                                                   2539430
Name                                                 Black Dragon Mage Playtest
Release date                                                        Aug 1, 2023
Estimated owners                                                          0 - 0
Peak CCU                                                                      0
Required age                                                                  0
Price                                                                       0.0
Discount                                                                      0
DLC count                                                                     0
About the game                                                              NaN
Supported languages                                                          []
Full audio languages                                                         []
Reviews                                                                     NaN
Header image                  https://shared.akamai.steamstatic.com/store_it...
Website                                                                     NaN
Support url                                                                 NaN
Support email                                                               NaN
Windows                                                                    True
Mac                                                                       False
Linux                                                                     False
Metacritic score                                                              0
Metacritic url                                                              NaN
User score                                                                    0
Positive                                                                      0
Negative                                                                      0
Score rank                                                                  NaN
Achievements                                                                  0
Recommendations                                                               0
Notes                                                                       NaN
Average playtime forever                                                      0
Average playtime two weeks                                                    0
Median playtime forever                                                       0
Median playtime two weeks                                                     0
Developers                                                                  NaN
Publishers                                                                  NaN
Categories                                                                  NaN
Genres                                                                      NaN
Tags                                                                        NaN
Screenshots                   https://shared.akamai.steamstatic.com/store_it...
Movies                                                                      NaN
Name: 0, dtype: object